// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/dex/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	TradeFee              cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=trade_fee,json=tradeFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"trade_fee"`
	OrderFee              cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=order_fee,json=orderFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"order_fee"`
	ReserveShare          cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=reserve_share,json=reserveShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reserve_share"`
	VirtualLiquidityDecay cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=virtual_liquidity_decay,json=virtualLiquidityDecay,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"virtual_liquidity_decay"`
	TradeAmountDecay      cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=trade_amount_decay,json=tradeAmountDecay,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"trade_amount_decay"`
	DiscountLevels        []*DiscountLevel            `protobuf:"bytes,6,rep,name=discount_levels,json=discountLevels,proto3" json:"discount_levels,omitempty"`
	MaxOrderLife          uint64                      `protobuf:"varint,7,opt,name=max_order_life,json=maxOrderLife,proto3" json:"max_order_life,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42254e805f59482, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDiscountLevels() []*DiscountLevel {
	if m != nil {
		return m.DiscountLevels
	}
	return nil
}

func (m *Params) GetMaxOrderLife() uint64 {
	if m != nil {
		return m.MaxOrderLife
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "kopi.dex.Params")
}

func init() { proto.RegisterFile("kopi/dex/params.proto", fileDescriptor_a42254e805f59482) }

var fileDescriptor_a42254e805f59482 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x13, 0x6f, 0xad, 0xd7, 0xb1, 0x5e, 0xbd, 0xc1, 0x4b, 0x43, 0xc5, 0xb4, 0xa8, 0x48,
	0x11, 0x4c, 0x40, 0x77, 0xae, 0x6a, 0x29, 0xe2, 0x22, 0xa0, 0xd6, 0x9d, 0x2e, 0xc2, 0x34, 0x73,
	0x9a, 0x0e, 0xcd, 0x74, 0xe2, 0xcc, 0xa4, 0x24, 0xaf, 0xd0, 0x95, 0x8f, 0xe0, 0x23, 0xf8, 0x18,
	0x5d, 0x76, 0x29, 0x2e, 0x8a, 0xb4, 0x0b, 0x7d, 0x0c, 0x99, 0x49, 0x2a, 0x75, 0x57, 0x37, 0xe1,
	0xe4, 0x9c, 0x7c, 0x5f, 0xe0, 0x9c, 0x1f, 0x5d, 0xcd, 0x79, 0x46, 0x03, 0x02, 0x45, 0x90, 0x61,
	0x81, 0x99, 0xf4, 0x33, 0xc1, 0x15, 0x77, 0xce, 0x75, 0xdb, 0x27, 0x50, 0x74, 0x2e, 0x31, 0xa3,
	0x0b, 0x1e, 0x98, 0x67, 0x35, 0xec, 0xdc, 0x4b, 0x78, 0xc2, 0x4d, 0x19, 0xe8, 0xaa, 0xee, 0x3e,
	0xf8, 0x6b, 0x22, 0x54, 0xc6, 0x3c, 0x5f, 0xa8, 0x28, 0x85, 0x25, 0xa4, 0xd5, 0xf8, 0xe1, 0xaa,
	0x81, 0x9a, 0xef, 0xcc, 0x2f, 0x9c, 0x01, 0xba, 0xa9, 0x04, 0x26, 0x10, 0x4d, 0x01, 0x5c, 0xbb,
	0x67, 0xf7, 0x5b, 0xc3, 0x47, 0xeb, 0x6d, 0xd7, 0xfa, 0xb1, 0xed, 0xde, 0x8f, 0xb9, 0x64, 0x5c,
	0x4a, 0x32, 0xf7, 0x29, 0x0f, 0x18, 0x56, 0x33, 0x3f, 0x84, 0x04, 0xc7, 0xe5, 0x08, 0xe2, 0xf1,
	0xb9, 0xa1, 0x5e, 0x03, 0x68, 0x03, 0x17, 0x04, 0x84, 0x31, 0x5c, 0xfb, 0x0f, 0x83, 0xa1, 0xb4,
	0xe1, 0x0d, 0xba, 0x2d, 0x40, 0x82, 0x58, 0x42, 0x24, 0x67, 0x58, 0x80, 0x7b, 0x76, 0xba, 0xa5,
	0x55, 0x93, 0x1f, 0x34, 0xe8, 0x7c, 0x42, 0xed, 0x25, 0x15, 0x2a, 0xc7, 0x69, 0x94, 0xd2, 0xcf,
	0x39, 0x25, 0x54, 0x95, 0x11, 0x81, 0x18, 0x97, 0x6e, 0xe3, 0x74, 0xe7, 0x55, 0xed, 0x08, 0x0f,
	0x8a, 0x91, 0x36, 0x38, 0xef, 0x91, 0x53, 0xad, 0x0a, 0x33, 0xb3, 0xd1, 0xca, 0x7b, 0xfd, 0x74,
	0xef, 0x5d, 0x83, 0xbf, 0x32, 0x74, 0xa5, 0x1c, 0xa0, 0x3b, 0xff, 0x1e, 0x48, 0xba, 0xcd, 0xde,
	0x59, 0xff, 0xd6, 0xf3, 0xb6, 0x7f, 0x38, 0xba, 0x3f, 0xaa, 0x3f, 0x08, 0xf5, 0x7c, 0x7c, 0x41,
	0x8e, 0x5f, 0xa5, 0xf3, 0x18, 0x5d, 0x30, 0x5c, 0x44, 0xd5, 0x05, 0x52, 0x3a, 0x05, 0xf7, 0x46,
	0xcf, 0xee, 0x37, 0xc6, 0x2d, 0x86, 0x8b, 0xb7, 0xba, 0x19, 0xd2, 0x29, 0xbc, 0xec, 0xfc, 0xfe,
	0xda, 0xb5, 0x57, 0xbf, 0xbe, 0x3d, 0xbd, 0x34, 0xc1, 0x28, 0x4c, 0x34, 0xaa, 0x04, 0x0c, 0x07,
	0xeb, 0x9d, 0x67, 0x6f, 0x76, 0x9e, 0xfd, 0x73, 0xe7, 0xd9, 0x5f, 0xf6, 0x9e, 0xb5, 0xd9, 0x7b,
	0xd6, 0xf7, 0xbd, 0x67, 0x7d, 0x7c, 0x92, 0x50, 0x35, 0xcb, 0x27, 0x7e, 0xcc, 0x59, 0xa0, 0xb9,
	0x67, 0x8c, 0x2f, 0xa0, 0x0c, 0x8e, 0x14, 0xaa, 0xcc, 0x40, 0x4e, 0x9a, 0x26, 0x55, 0x2f, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x33, 0x6d, 0xe4, 0x10, 0xc0, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TradeFee.Equal(that1.TradeFee) {
		return false
	}
	if !this.OrderFee.Equal(that1.OrderFee) {
		return false
	}
	if !this.ReserveShare.Equal(that1.ReserveShare) {
		return false
	}
	if !this.VirtualLiquidityDecay.Equal(that1.VirtualLiquidityDecay) {
		return false
	}
	if !this.TradeAmountDecay.Equal(that1.TradeAmountDecay) {
		return false
	}
	if len(this.DiscountLevels) != len(that1.DiscountLevels) {
		return false
	}
	for i := range this.DiscountLevels {
		if !this.DiscountLevels[i].Equal(that1.DiscountLevels[i]) {
			return false
		}
	}
	if this.MaxOrderLife != that1.MaxOrderLife {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxOrderLife != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxOrderLife))
		i--
		dAtA[i] = 0x38
	}
	if len(m.DiscountLevels) > 0 {
		for iNdEx := len(m.DiscountLevels) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DiscountLevels[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size := m.TradeAmountDecay.Size()
		i -= size
		if _, err := m.TradeAmountDecay.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.VirtualLiquidityDecay.Size()
		i -= size
		if _, err := m.VirtualLiquidityDecay.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.ReserveShare.Size()
		i -= size
		if _, err := m.ReserveShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.OrderFee.Size()
		i -= size
		if _, err := m.OrderFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.TradeFee.Size()
		i -= size
		if _, err := m.TradeFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TradeFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.OrderFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ReserveShare.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.VirtualLiquidityDecay.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TradeAmountDecay.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.DiscountLevels) > 0 {
		for _, e := range m.DiscountLevels {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.MaxOrderLife != 0 {
		n += 1 + sovParams(uint64(m.MaxOrderLife))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TradeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OrderFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReserveShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualLiquidityDecay", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VirtualLiquidityDecay.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeAmountDecay", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TradeAmountDecay.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountLevels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DiscountLevels = append(m.DiscountLevels, &DiscountLevel{})
			if err := m.DiscountLevels[len(m.DiscountLevels)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderLife", wireType)
			}
			m.MaxOrderLife = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOrderLife |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
