// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/strategies/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the pt module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params              Params                    `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	ArbitrageDenoms     []*ArbitrageDenom         `protobuf:"bytes,2,rep,name=arbitrage_denoms,json=arbitrageDenoms,proto3" json:"arbitrage_denoms,omitempty"`
	Automations         []*Automation             `protobuf:"bytes,3,rep,name=automations,proto3" json:"automations,omitempty"`
	AutomationFunds     []*GenesisAutomationFunds `protobuf:"bytes,4,rep,name=automation_funds,json=automationFunds,proto3" json:"automation_funds,omitempty"`
	AutomationNextIndex uint64                    `protobuf:"varint,5,opt,name=automation_next_index,json=automationNextIndex,proto3" json:"automation_next_index,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f3386718f510e0a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetArbitrageDenoms() []*ArbitrageDenom {
	if m != nil {
		return m.ArbitrageDenoms
	}
	return nil
}

func (m *GenesisState) GetAutomations() []*Automation {
	if m != nil {
		return m.Automations
	}
	return nil
}

func (m *GenesisState) GetAutomationFunds() []*GenesisAutomationFunds {
	if m != nil {
		return m.AutomationFunds
	}
	return nil
}

func (m *GenesisState) GetAutomationNextIndex() uint64 {
	if m != nil {
		return m.AutomationNextIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "kopi.strategies.GenesisState")
}

func init() { proto.RegisterFile("kopi/strategies/genesis.proto", fileDescriptor_7f3386718f510e0a) }

var fileDescriptor_7f3386718f510e0a = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x33, 0x6d, 0x6f, 0xe1, 0x4e, 0x85, 0xd6, 0xa8, 0x18, 0xaa, 0xa6, 0xd5, 0x8d, 0x45,
	0x68, 0x02, 0x75, 0x27, 0xb8, 0xb0, 0x88, 0x45, 0x17, 0x22, 0x71, 0xe7, 0xa6, 0x4c, 0xed, 0x18,
	0x07, 0xc9, 0x4c, 0xc8, 0x9c, 0x42, 0xfa, 0x16, 0x3e, 0x86, 0x4b, 0x1f, 0xa3, 0xcb, 0x2e, 0xdd,
	0x28, 0xd2, 0x2e, 0x7c, 0x0d, 0xc9, 0x74, 0x6c, 0xd2, 0x66, 0x13, 0xce, 0xcc, 0xff, 0xe5, 0xcb,
	0x1f, 0x0e, 0x3e, 0x78, 0x11, 0x21, 0x73, 0x25, 0x44, 0x04, 0xa8, 0xcf, 0xa8, 0x74, 0x7d, 0xca,
	0xa9, 0x64, 0xd2, 0x09, 0x23, 0x01, 0xc2, 0xac, 0x26, 0xb1, 0x93, 0xc6, 0xf5, 0x4d, 0x12, 0x30,
	0x2e, 0x5c, 0xf5, 0x5c, 0x30, 0xf5, 0x6d, 0x5f, 0xf8, 0x42, 0x8d, 0x6e, 0x32, 0xe9, 0xdb, 0xfd,
	0x75, 0x71, 0x48, 0x22, 0x12, 0x68, 0x6f, 0xbd, 0xb1, 0x9e, 0x92, 0x68, 0xc0, 0x20, 0x22, 0x3e,
	0xd5, 0xc0, 0x61, 0x0e, 0x18, 0x81, 0x08, 0x08, 0x30, 0xc1, 0xb5, 0xe3, 0xe8, 0xb3, 0x80, 0x37,
	0x7a, 0x8b, 0xb6, 0xf7, 0x40, 0x80, 0x9a, 0x67, 0xb8, 0xbc, 0xf8, 0x88, 0x85, 0x9a, 0xa8, 0x55,
	0xe9, 0xec, 0x3a, 0x6b, 0xed, 0x9d, 0x3b, 0x15, 0x77, 0xff, 0x4f, 0xbe, 0x1a, 0xc6, 0xdb, 0xcf,
	0xfb, 0x09, 0xf2, 0xf4, 0x1b, 0xe6, 0x0d, 0xae, 0x2d, 0x2b, 0xf4, 0x87, 0x94, 0x8b, 0x40, 0x5a,
	0x85, 0x66, 0xb1, 0x55, 0xe9, 0x34, 0x72, 0x96, 0x8b, 0x3f, 0xf0, 0x32, 0xe1, 0xbc, 0x2a, 0x59,
	0x39, 0x4b, 0xf3, 0x1c, 0x57, 0x32, 0x6d, 0xad, 0xa2, 0xd2, 0xec, 0xe5, 0x35, 0x4b, 0xc6, 0xcb,
	0xf2, 0xa6, 0x87, 0x6b, 0xe9, 0xb1, 0xff, 0x34, 0xe2, 0x43, 0x69, 0x95, 0x94, 0xe3, 0x38, 0xe7,
	0xd0, 0xff, 0x9f, 0xaa, 0xae, 0x12, 0xdc, 0xab, 0x92, 0xd5, 0x0b, 0xb3, 0x83, 0x77, 0x32, 0x4e,
	0x4e, 0x63, 0xe8, 0x33, 0x3e, 0xa4, 0xb1, 0xf5, 0xaf, 0x89, 0x5a, 0x25, 0x6f, 0x2b, 0x0d, 0x6f,
	0x69, 0x0c, 0xd7, 0x49, 0xd4, 0xed, 0x4d, 0x66, 0x36, 0x9a, 0xce, 0x6c, 0xf4, 0x3d, 0xb3, 0xd1,
	0xeb, 0xdc, 0x36, 0xa6, 0x73, 0xdb, 0xf8, 0x98, 0xdb, 0xc6, 0x43, 0xdb, 0x67, 0xf0, 0x3c, 0x1a,
	0x38, 0x8f, 0x22, 0x70, 0x93, 0x46, 0xed, 0x40, 0x70, 0x3a, 0x56, 0xa3, 0x1b, 0x67, 0x97, 0x06,
	0xe3, 0x90, 0xca, 0x41, 0x59, 0xed, 0xeb, 0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0xff, 0x7e, 0x5b,
	0x69, 0x6c, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AutomationNextIndex != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AutomationNextIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AutomationFunds) > 0 {
		for iNdEx := len(m.AutomationFunds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AutomationFunds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Automations) > 0 {
		for iNdEx := len(m.Automations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Automations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ArbitrageDenoms) > 0 {
		for iNdEx := len(m.ArbitrageDenoms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ArbitrageDenoms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ArbitrageDenoms) > 0 {
		for _, e := range m.ArbitrageDenoms {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Automations) > 0 {
		for _, e := range m.Automations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AutomationFunds) > 0 {
		for _, e := range m.AutomationFunds {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.AutomationNextIndex != 0 {
		n += 1 + sovGenesis(uint64(m.AutomationNextIndex))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbitrageDenoms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArbitrageDenoms = append(m.ArbitrageDenoms, &ArbitrageDenom{})
			if err := m.ArbitrageDenoms[len(m.ArbitrageDenoms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Automations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Automations = append(m.Automations, &Automation{})
			if err := m.Automations[len(m.Automations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutomationFunds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AutomationFunds = append(m.AutomationFunds, &GenesisAutomationFunds{})
			if err := m.AutomationFunds[len(m.AutomationFunds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutomationNextIndex", wireType)
			}
			m.AutomationNextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AutomationNextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
