// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kopi/mm/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	CollateralDiscount      cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=collateral_discount,json=collateralDiscount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"collateral_discount"`
	MinRedemptionFee        cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=min_redemption_fee,json=minRedemptionFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_redemption_fee"`
	MaxRedemptionFee        cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=max_redemption_fee,json=maxRedemptionFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_redemption_fee"`
	ProtocolShare           cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=protocol_share,json=protocolShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"protocol_share"`
	MinInterestRate         cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=min_interest_rate,json=minInterestRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_interest_rate"`
	A                       cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=a,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"a"`
	B                       cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=b,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"b"`
	BlockSpeedMovingAverage cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=block_speed_moving_average,json=blockSpeedMovingAverage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"block_speed_moving_average"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_15f556eedf9a875f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "kopi.mm.Params")
}

func init() { proto.RegisterFile("kopi/mm/params.proto", fileDescriptor_15f556eedf9a875f) }

var fileDescriptor_15f556eedf9a875f = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd2, 0xcf, 0x6b, 0x14, 0x31,
	0x14, 0xc0, 0xf1, 0x8d, 0xda, 0xad, 0x04, 0x7f, 0xb4, 0xb1, 0xe0, 0xb8, 0xc2, 0xac, 0x28, 0x82,
	0x08, 0xce, 0x20, 0xde, 0xbc, 0x88, 0xa5, 0x08, 0x8a, 0xa2, 0x6e, 0x3d, 0x79, 0x89, 0x6f, 0xb2,
	0xcf, 0xd9, 0xb0, 0x93, 0xbc, 0x21, 0x49, 0xcb, 0xee, 0xdd, 0x93, 0x27, 0xff, 0x04, 0xff, 0x04,
	0xff, 0x8c, 0x1e, 0x7b, 0x14, 0x0f, 0x45, 0x76, 0x0f, 0xfa, 0x67, 0x48, 0xb2, 0xd5, 0x62, 0x4f,
	0xd3, 0xcb, 0x10, 0xde, 0xf0, 0xfd, 0xc0, 0x4c, 0x1e, 0xdf, 0x9a, 0x52, 0xab, 0x4b, 0x63, 0xca,
	0x16, 0x1c, 0x18, 0x5f, 0xb4, 0x8e, 0x02, 0x89, 0xf5, 0x38, 0x2d, 0x8c, 0x19, 0x6c, 0x82, 0xd1,
	0x96, 0xca, 0xf4, 0x5c, 0xbd, 0x1b, 0x6c, 0xd5, 0x54, 0x53, 0x3a, 0x96, 0xf1, 0xb4, 0x9a, 0xde,
	0xfe, 0xb4, 0xc6, 0xfb, 0x6f, 0x12, 0x21, 0xde, 0xf1, 0x6b, 0x8a, 0x9a, 0x06, 0x02, 0x3a, 0x68,
	0xe4, 0x58, 0x7b, 0x45, 0x7b, 0x36, 0x64, 0xec, 0x16, 0xbb, 0x77, 0x69, 0xfb, 0xce, 0xc1, 0xd1,
	0xb0, 0xf7, 0xe3, 0x68, 0x78, 0x53, 0x91, 0x37, 0xe4, 0xfd, 0x78, 0x5a, 0x68, 0x2a, 0x0d, 0x84,
	0x49, 0xf1, 0x12, 0x6b, 0x50, 0xf3, 0x1d, 0x54, 0x23, 0x71, 0xd2, 0xef, 0x1c, 0xe7, 0xe2, 0x2d,
	0x17, 0x46, 0x5b, 0xe9, 0x70, 0x8c, 0xa6, 0x0d, 0x9a, 0xac, 0xfc, 0x88, 0x98, 0x9d, 0xeb, 0x8e,
	0x6e, 0x18, 0x6d, 0x47, 0xff, 0xea, 0x67, 0x88, 0x89, 0x84, 0xd9, 0x69, 0xf2, 0xfc, 0x59, 0x48,
	0x98, 0xfd, 0x4f, 0xbe, 0xe0, 0x57, 0xd2, 0xff, 0x50, 0xd4, 0x48, 0x3f, 0x01, 0x87, 0xd9, 0x85,
	0xee, 0xdc, 0xe5, 0xbf, 0xe9, 0x6e, 0x2c, 0xc5, 0x6b, 0xbe, 0x19, 0xbf, 0x58, 0xdb, 0x80, 0x0e,
	0x7d, 0x90, 0x0e, 0x02, 0x66, 0x6b, 0xdd, 0xb9, 0xab, 0x46, 0xdb, 0xe7, 0xc7, 0xf1, 0x08, 0x02,
	0x8a, 0x87, 0x9c, 0x41, 0xd6, 0xef, 0x0e, 0x30, 0x88, 0x49, 0x95, 0xad, 0x9f, 0x21, 0xa9, 0xc4,
	0x07, 0x3e, 0xa8, 0x1a, 0x52, 0x53, 0xe9, 0x5b, 0xc4, 0xb1, 0x34, 0xb4, 0xaf, 0x6d, 0x2d, 0x61,
	0x1f, 0x1d, 0xd4, 0x98, 0x5d, 0xec, 0x6e, 0x5d, 0x4f, 0xcc, 0x6e, 0x54, 0x5e, 0x25, 0xe4, 0xe9,
	0xca, 0x78, 0x7c, 0xe3, 0xf7, 0xd7, 0x21, 0xfb, 0xfc, 0xeb, 0xdb, 0xfd, 0x8d, 0xb4, 0xbc, 0xb3,
	0xb8, 0xbe, 0xab, 0xdd, 0xdb, 0x7e, 0x72, 0xb0, 0xc8, 0xd9, 0xe1, 0x22, 0x67, 0x3f, 0x17, 0x39,
	0xfb, 0xb2, 0xcc, 0x7b, 0x87, 0xcb, 0xbc, 0xf7, 0x7d, 0x99, 0xf7, 0xde, 0xdf, 0xad, 0x75, 0x98,
	0xec, 0x55, 0x85, 0x22, 0x53, 0xc6, 0xec, 0x81, 0x21, 0x8b, 0xf3, 0xf2, 0x44, 0x08, 0xf3, 0x16,
	0x7d, 0xd5, 0x4f, 0x77, 0xf0, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x4e, 0x31, 0x6b,
	0x18, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CollateralDiscount.Equal(that1.CollateralDiscount) {
		return false
	}
	if !this.MinRedemptionFee.Equal(that1.MinRedemptionFee) {
		return false
	}
	if !this.MaxRedemptionFee.Equal(that1.MaxRedemptionFee) {
		return false
	}
	if !this.ProtocolShare.Equal(that1.ProtocolShare) {
		return false
	}
	if !this.MinInterestRate.Equal(that1.MinInterestRate) {
		return false
	}
	if !this.A.Equal(that1.A) {
		return false
	}
	if !this.B.Equal(that1.B) {
		return false
	}
	if !this.BlockSpeedMovingAverage.Equal(that1.BlockSpeedMovingAverage) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BlockSpeedMovingAverage.Size()
		i -= size
		if _, err := m.BlockSpeedMovingAverage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.B.Size()
		i -= size
		if _, err := m.B.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.A.Size()
		i -= size
		if _, err := m.A.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinInterestRate.Size()
		i -= size
		if _, err := m.MinInterestRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.ProtocolShare.Size()
		i -= size
		if _, err := m.ProtocolShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MaxRedemptionFee.Size()
		i -= size
		if _, err := m.MaxRedemptionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinRedemptionFee.Size()
		i -= size
		if _, err := m.MinRedemptionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.CollateralDiscount.Size()
		i -= size
		if _, err := m.CollateralDiscount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CollateralDiscount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinRedemptionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxRedemptionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ProtocolShare.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinInterestRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.A.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.B.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BlockSpeedMovingAverage.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralDiscount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralDiscount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRedemptionFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinRedemptionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRedemptionFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxRedemptionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProtocolShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInterestRate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinInterestRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.A.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.B.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockSpeedMovingAverage", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockSpeedMovingAverage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
